import '../strings.dart';

class SearchModel{
  String? img;
  SearchModel({this.img});
}

class SearchImgBox{
  List<SearchModel> imgBox=[
    SearchModel(img: Strings.image1),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image2),
    SearchModel(img: Strings.post2),
    SearchModel(img: Strings.image3),
    SearchModel(img: Strings.post3),
    SearchModel(img: Strings.image4),
    SearchModel(img: Strings.post4),
    SearchModel(img: Strings.image5),
    SearchModel(img: Strings.post5),
    SearchModel(img: Strings.image6),
    SearchModel(img: Strings.post6),
    SearchModel(img: Strings.image7),
    SearchModel(img: Strings.post7),
    SearchModel(img: Strings.image8),
    SearchModel(img: Strings.post8),
    SearchModel(img: Strings.image9),
    // SearchModel(img: Strings.post9),
    SearchModel(img: Strings.image10),
    // SearchModel(img: Strings.post10),
    SearchModel(img: Strings.image11),
    // SearchModel(img: Strings.post11),
    SearchModel(img: Strings.image12),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image1),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image2),
    SearchModel(img: Strings.post2),
    SearchModel(img: Strings.image3),
    SearchModel(img: Strings.post3),
    SearchModel(img: Strings.image4),
    SearchModel(img: Strings.post4),
    SearchModel(img: Strings.image5),
    SearchModel(img: Strings.post5),
    SearchModel(img: Strings.image6),
    SearchModel(img: Strings.post6),
    SearchModel(img: Strings.image7),
    SearchModel(img: Strings.post7),
    SearchModel(img: Strings.image8),
    SearchModel(img: Strings.post8),
    SearchModel(img: Strings.image9),
    // SearchModel(img: Strings.post9),
    SearchModel(img: Strings.image10),
    // SearchModel(img: Strings.post10),
    SearchModel(img: Strings.image11),
    // SearchModel(img: Strings.post11),
    SearchModel(img: Strings.image12),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image1),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image2),
    SearchModel(img: Strings.post2),
    SearchModel(img: Strings.image3),
    SearchModel(img: Strings.post3),
    SearchModel(img: Strings.image4),
    SearchModel(img: Strings.post4),
    SearchModel(img: Strings.image5),
    SearchModel(img: Strings.post5),
    SearchModel(img: Strings.image6),
    SearchModel(img: Strings.post6),
    SearchModel(img: Strings.image7),
    SearchModel(img: Strings.post7),
    SearchModel(img: Strings.image8),
    SearchModel(img: Strings.post8),
    SearchModel(img: Strings.image9),
    // SearchModel(img: Strings.post9),
    SearchModel(img: Strings.image10),
    // SearchModel(img: Strings.post10),
    SearchModel(img: Strings.image11),
    // SearchModel(img: Strings.post11),
    SearchModel(img: Strings.image12),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image1),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image2),
    SearchModel(img: Strings.post2),
    SearchModel(img: Strings.image3),
    SearchModel(img: Strings.post3),
    SearchModel(img: Strings.image4),
    SearchModel(img: Strings.post4),
    SearchModel(img: Strings.image5),
    SearchModel(img: Strings.post5),
    SearchModel(img: Strings.image6),
    SearchModel(img: Strings.post6),
    SearchModel(img: Strings.image7),
    SearchModel(img: Strings.post7),
    SearchModel(img: Strings.image8),
    SearchModel(img: Strings.post8),
    SearchModel(img: Strings.image9),
    // SearchModel(img: Strings.post9),
    SearchModel(img: Strings.image10),
    // SearchModel(img: Strings.post10),
    SearchModel(img: Strings.image11),
    // SearchModel(img: Strings.post11),
    SearchModel(img: Strings.image12),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image1),
    SearchModel(img: Strings.post1),
    SearchModel(img: Strings.image2),
    SearchModel(img: Strings.post2),
    SearchModel(img: Strings.image3),
    SearchModel(img: Strings.post3),
    SearchModel(img: Strings.image4),
    SearchModel(img: Strings.post4),
    SearchModel(img: Strings.image5),
    SearchModel(img: Strings.post5),
    SearchModel(img: Strings.image6),
    SearchModel(img: Strings.post6),
    SearchModel(img: Strings.image7),
    SearchModel(img: Strings.post7),
    SearchModel(img: Strings.image8),
    SearchModel(img: Strings.post8),
    SearchModel(img: Strings.image9),
    // SearchModel(img: Strings.post9),
    SearchModel(img: Strings.image10),
    // SearchModel(img: Strings.post10),
    SearchModel(img: Strings.image11),
    // SearchModel(img: Strings.post11),
    SearchModel(img: Strings.image12),
    SearchModel(img: Strings.post1),
  ];
}